name: Ansible Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: ""
        override-deps: |
          ansible==2.10.3
          ansible-lint==5.0.7
        args: -c .ansible-lint